# Generated by Django 3.2.12 on 2022-04-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('P', 'Phone'), ('E', 'Email'), ('F', 'Facebook'), ('L', 'Line'), ('T', 'Twitter'), ('I', 'Instagram'), ('W', 'Website'), ('D', 'Discord'), ('O', 'Other')], max_length=1)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_en', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Master', 'Master')], max_length=10)),
                ('prefix_th', models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('เด็กชาย', 'เด็กชาย')], max_length=10)),
                ('first_name_th', models.CharField(max_length=50)),
                ('last_name_th', models.CharField(max_length=50)),
                ('middle_name_th', models.CharField(max_length=50)),
                ('first_name_en', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(max_length=50)),
                ('middle_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField()),
                ('citizen_id', models.CharField(max_length=13)),
                ('contact', models.ManyToManyField(blank=True, null=True, to='people.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=5)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=5)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='people.person')),
            ],
        ),
    ]
