# Generated by Django 3.2.12 on 2022-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name_th',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
