# Generated by Django 3.2.12 on 2022-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_middle_name_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='of', to='people.Contact'),
        ),
    ]
