# Generated by Django 3.2.12 on 2022-04-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='contact',
            new_name='contacts',
        ),
    ]
